export default {
    onboard: "ONBOARD",
    signup: "SIGN_UP",
    login: "SIGN_IN",
    home: "HOME",
    loyalty: "LOYALTY",
    discount: "DISCOUNT CARDS",
    dis: "DISCOUNT",
    discountDetails: "DISCOUNTCARD DETAILS",
    wallet: "WALLET",
    wallets: "WLT",
    gifts: "GIFTS",
    giftDetail: "GIFTCARD DETAILS",
    feed: "FEED",
    giftFeed: "GIFT CARDS",
    loyaltyDetail: "LOYALTYCARD DETAILS",
    loyaltyFeed: "LOYALTY CARDS",
    walletDetail: "CARD DETAILS",
    forgotPassword: "FORGOT_PASSWORD",
    settings: "SETTINGS",
    promotions: "COMPETITIONS",
    promo: "CMPT",
    promotion_details: "COMPETITION DETAILS",
    analytics: "History",
    contact: "CONTACT",
    about: "ABOUT",
    verification: "PRODUCT  VERIFICATION",
    faqs: "FAQs"
}